# Generated by Django 4.0.6 on 2023-07-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('location', models.TextField(blank=True)),
                ('num_items', models.IntegerField(default=1)),
                ('item_count', models.TextField()),
                ('status', models.TextField(choices=[('AVAIL', 'available'), ('UNAVAIL', 'unavailable')], default='UNAVAIL')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
