# Generated by Django 4.0.6 on 2023-07-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_alter_itemgroup_item_count_alter_itemgroup_num_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemgroup',
            name='slug',
            field=models.SlugField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
