# Generated by Django 4.0.6 on 2023-07-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_itemgroup_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemgroup',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
