# Generated by Django 4.0.6 on 2023-07-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_alter_itemgroup_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemgroup',
            name='slug',
            field=models.SlugField(blank=True, default=0, unique=True),
            preserve_default=False,
        ),
    ]
