# Generated by Django 4.0.6 on 2023-07-13 00:09

from django.db import migrations
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_alter_itemgroup_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemgroup',
            name='id',
        ),
        migrations.RemoveField(
            model_name='itemgroup',
            name='slug',
        ),
        migrations.AddField(
            model_name='itemgroup',
            name='tslug',
            field=hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', default=0, min_length=7, prefix='', primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
