# Generated by Django 4.0.6 on 2023-07-29 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_remove_itemgroup_id_remove_itemgroup_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemgroup',
            name='tslug',
        ),
        migrations.AddField(
            model_name='itemgroup',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemgroup',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
