# Generated by Django 4.0.6 on 2023-08-07 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_remove_itemgroup_tslug_itemgroup_id_itemgroup_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.TextField(blank=True)),
                ('actor', models.TextField(blank=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('num_items', models.IntegerField(default=0)),
            ],
        ),
    ]
