# Generated by Django 4.0.6 on 2023-08-08 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0010_event_item_group_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='item_group_id',
            new_name='item_group',
        ),
    ]
